// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package scraper

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Alias, b.ko.Spec.Alias) {
		delta.Add("Spec.Alias", a.ko.Spec.Alias, b.ko.Spec.Alias)
	} else if a.ko.Spec.Alias != nil && b.ko.Spec.Alias != nil {
		if *a.ko.Spec.Alias != *b.ko.Spec.Alias {
			delta.Add("Spec.Alias", a.ko.Spec.Alias, b.ko.Spec.Alias)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Destination, b.ko.Spec.Destination) {
		delta.Add("Spec.Destination", a.ko.Spec.Destination, b.ko.Spec.Destination)
	} else if a.ko.Spec.Destination != nil && b.ko.Spec.Destination != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Destination.AmpConfiguration, b.ko.Spec.Destination.AmpConfiguration) {
			delta.Add("Spec.Destination.AmpConfiguration", a.ko.Spec.Destination.AmpConfiguration, b.ko.Spec.Destination.AmpConfiguration)
		} else if a.ko.Spec.Destination.AmpConfiguration != nil && b.ko.Spec.Destination.AmpConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Destination.AmpConfiguration.WorkspaceARN, b.ko.Spec.Destination.AmpConfiguration.WorkspaceARN) {
				delta.Add("Spec.Destination.AmpConfiguration.WorkspaceARN", a.ko.Spec.Destination.AmpConfiguration.WorkspaceARN, b.ko.Spec.Destination.AmpConfiguration.WorkspaceARN)
			} else if a.ko.Spec.Destination.AmpConfiguration.WorkspaceARN != nil && b.ko.Spec.Destination.AmpConfiguration.WorkspaceARN != nil {
				if *a.ko.Spec.Destination.AmpConfiguration.WorkspaceARN != *b.ko.Spec.Destination.AmpConfiguration.WorkspaceARN {
					delta.Add("Spec.Destination.AmpConfiguration.WorkspaceARN", a.ko.Spec.Destination.AmpConfiguration.WorkspaceARN, b.ko.Spec.Destination.AmpConfiguration.WorkspaceARN)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Source, b.ko.Spec.Source) {
		delta.Add("Spec.Source", a.ko.Spec.Source, b.ko.Spec.Source)
	} else if a.ko.Spec.Source != nil && b.ko.Spec.Source != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Source.EKSConfiguration, b.ko.Spec.Source.EKSConfiguration) {
			delta.Add("Spec.Source.EKSConfiguration", a.ko.Spec.Source.EKSConfiguration, b.ko.Spec.Source.EKSConfiguration)
		} else if a.ko.Spec.Source.EKSConfiguration != nil && b.ko.Spec.Source.EKSConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Source.EKSConfiguration.ClusterARN, b.ko.Spec.Source.EKSConfiguration.ClusterARN) {
				delta.Add("Spec.Source.EKSConfiguration.ClusterARN", a.ko.Spec.Source.EKSConfiguration.ClusterARN, b.ko.Spec.Source.EKSConfiguration.ClusterARN)
			} else if a.ko.Spec.Source.EKSConfiguration.ClusterARN != nil && b.ko.Spec.Source.EKSConfiguration.ClusterARN != nil {
				if *a.ko.Spec.Source.EKSConfiguration.ClusterARN != *b.ko.Spec.Source.EKSConfiguration.ClusterARN {
					delta.Add("Spec.Source.EKSConfiguration.ClusterARN", a.ko.Spec.Source.EKSConfiguration.ClusterARN, b.ko.Spec.Source.EKSConfiguration.ClusterARN)
				}
			}
			if len(a.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs) != len(b.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs) {
				delta.Add("Spec.Source.EKSConfiguration.SecurityGroupIDs", a.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs, b.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs)
			} else if len(a.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs, b.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs) {
					delta.Add("Spec.Source.EKSConfiguration.SecurityGroupIDs", a.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs, b.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs)
				}
			}
			if len(a.ko.Spec.Source.EKSConfiguration.SubnetIDs) != len(b.ko.Spec.Source.EKSConfiguration.SubnetIDs) {
				delta.Add("Spec.Source.EKSConfiguration.SubnetIDs", a.ko.Spec.Source.EKSConfiguration.SubnetIDs, b.ko.Spec.Source.EKSConfiguration.SubnetIDs)
			} else if len(a.ko.Spec.Source.EKSConfiguration.SubnetIDs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.Source.EKSConfiguration.SubnetIDs, b.ko.Spec.Source.EKSConfiguration.SubnetIDs) {
					delta.Add("Spec.Source.EKSConfiguration.SubnetIDs", a.ko.Spec.Source.EKSConfiguration.SubnetIDs, b.ko.Spec.Source.EKSConfiguration.SubnetIDs)
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Configuration, b.ko.Spec.Configuration) {
		delta.Add("Spec.Configuration", a.ko.Spec.Configuration, b.ko.Spec.Configuration)
	} else if a.ko.Spec.Configuration != nil && b.ko.Spec.Configuration != nil {
		if *a.ko.Spec.Configuration != *b.ko.Spec.Configuration {
			delta.Add("Spec.Configuration", a.ko.Spec.Configuration, b.ko.Spec.Configuration)
		}
	}

	return delta
}
