// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package scraper

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/prometheusservice-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=prometheusservice.services.k8s.aws,resources=workspaces,verbs=get;list
// +kubebuilder:rbac:groups=prometheusservice.services.k8s.aws,resources=workspaces/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.Destination != nil {
		if ko.Spec.Destination.AmpConfiguration != nil {
			if ko.Spec.Destination.AmpConfiguration.WorkspaceRef != nil {
				ko.Spec.Destination.AmpConfiguration.WorkspaceARN = nil
			}
		}
	}

	return &resource{ko}
}

// EnsureReferences restores, onto a copy of `latest`, the cross-resource reference
// (*Ref) fields it is missing, taking them from `desired`. Only reference fields are
// written, so every concrete value on `latest` stands.
//
// A *Ref is a sibling of the concrete field it resolves into, so rebuilding the
// containing struct from an AWS API response drops it. That disables
// ClearResolvedReferences, which suppresses a resolved value only while the sibling
// *Ref is visible, so the spec patch would otherwise delete the declared *Ref and
// store the resolved value in its place.
//
// Only references reached through structs are restored, and each containing struct
// is created on `latest` when `desired` has it and `latest` does not -- generated
// set-output code nils a struct when the response omits it. A top-level *Ref needs
// no help, since generated set-output code overwrites only the concrete field. One
// reached through a list is not restored: it has no fixed address, and replacing the
// whole list would discard whatever the service populated inside it.
//
// Nothing is written unless `desired` actually holds the reference, so a source that
// declares none leaves `latest` untouched.
func (rm *resourceManager) EnsureReferences(
	desired acktypes.AWSResource,
	latest acktypes.AWSResource,
) acktypes.AWSResource {
	// Deep copy the source as well, so a reference handed over below does not
	// alias the caller's declared object.
	desiredKO := rm.concreteResource(desired).ko.DeepCopy()
	latestKO := rm.concreteResource(latest).ko.DeepCopy()

	if desiredKO.Spec.Destination != nil {
		if desiredKO.Spec.Destination.AmpConfiguration != nil {
			if desiredKO.Spec.Destination.AmpConfiguration.WorkspaceRef != nil {
				if latestKO.Spec.Destination == nil {
					latestKO.Spec.Destination = &svcapitypes.Destination{}
				}
				if latestKO.Spec.Destination.AmpConfiguration == nil {
					latestKO.Spec.Destination.AmpConfiguration = &svcapitypes.AmpConfiguration{}
				}
				if latestKO.Spec.Destination.AmpConfiguration.WorkspaceRef == nil {
					latestKO.Spec.Destination.AmpConfiguration.WorkspaceRef = desiredKO.Spec.Destination.AmpConfiguration.WorkspaceRef
				}
			}
		}
	}

	return &resource{latestKO}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForDestination_AmpConfiguration_WorkspaceARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.Scraper) error {

	if ko.Spec.Destination != nil {
		if ko.Spec.Destination.AmpConfiguration != nil {
			if ko.Spec.Destination.AmpConfiguration.WorkspaceRef != nil && ko.Spec.Destination.AmpConfiguration.WorkspaceARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Destination.AmpConfiguration.WorkspaceARN", "Destination.AmpConfiguration.WorkspaceRef")
			}
		}
	}
	return nil
}

// resolveReferenceForDestination_AmpConfiguration_WorkspaceARN reads the resource referenced
// from Destination.AmpConfiguration.WorkspaceRef field and sets the Destination.AmpConfiguration.WorkspaceARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForDestination_AmpConfiguration_WorkspaceARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Scraper,
) (hasReferences bool, err error) {
	if ko.Spec.Destination != nil {
		if ko.Spec.Destination.AmpConfiguration != nil {
			if ko.Spec.Destination.AmpConfiguration.WorkspaceRef != nil && ko.Spec.Destination.AmpConfiguration.WorkspaceRef.From != nil {
				hasReferences = true
				arr := ko.Spec.Destination.AmpConfiguration.WorkspaceRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Destination.AmpConfiguration.WorkspaceRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &svcapitypes.Workspace{}
				if err := getReferencedResourceState_Workspace(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Destination.AmpConfiguration.WorkspaceARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Workspace looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Workspace(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.Workspace,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Workspace",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Workspace",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Workspace",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Workspace",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}
