// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package scraper

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/amp"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/amp/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/prometheusservice-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Scraper{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeScraperOutput
	resp, err = rm.sdkapi.DescribeScraper(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeScraper", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	// Mirror of the create hook: surface the returned configuration blob as the
	// human-readable string the user supplied, so no drift is reported against it.
	if resp.Scraper.ScrapeConfiguration != nil {
		blob, ok := resp.Scraper.ScrapeConfiguration.(*svcsdktypes.ScrapeConfigurationMemberConfigurationBlob)
		if !ok {
			return nil, ackerr.NewTerminalError(fmt.Errorf(
				"unsupported scrape configuration type %T returned by DescribeScraper",
				resp.Scraper.ScrapeConfiguration,
			))
		}
		configuration := string(blob.Value)
		ko.Spec.Configuration = &configuration
	} else {
		ko.Spec.Configuration = nil
	}

	if resp.Scraper.Alias != nil {
		ko.Spec.Alias = resp.Scraper.Alias
	} else {
		ko.Spec.Alias = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Scraper.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Scraper.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Scraper.Destination != nil {
		f3 := &svcapitypes.Destination{}
		switch resp.Scraper.Destination.(type) {
		case *svcsdktypes.DestinationMemberAmpConfiguration:
			f3f0 := resp.Scraper.Destination.(*svcsdktypes.DestinationMemberAmpConfiguration)
			if f3f0 != nil {
				f3f0f0 := &svcapitypes.AmpConfiguration{}
				if f3f0.Value.WorkspaceArn != nil {
					f3f0f0.WorkspaceARN = f3f0.Value.WorkspaceArn
				}
				f3.AmpConfiguration = f3f0f0
			}
		}
		ko.Spec.Destination = f3
	} else {
		ko.Spec.Destination = nil
	}
	if resp.Scraper.RoleArn != nil {
		ko.Status.RoleARN = resp.Scraper.RoleArn
	} else {
		ko.Status.RoleARN = nil
	}
	if resp.Scraper.ScraperId != nil {
		ko.Status.ScraperID = resp.Scraper.ScraperId
	} else {
		ko.Status.ScraperID = nil
	}
	if resp.Scraper.Source != nil {
		f7 := &svcapitypes.Source{}
		switch resp.Scraper.Source.(type) {
		case *svcsdktypes.SourceMemberEksConfiguration:
			f7f0 := resp.Scraper.Source.(*svcsdktypes.SourceMemberEksConfiguration)
			if f7f0 != nil {
				f7f0f0 := &svcapitypes.EKSConfiguration{}
				if f7f0.Value.ClusterArn != nil {
					f7f0f0.ClusterARN = f7f0.Value.ClusterArn
				}
				if f7f0.Value.SecurityGroupIds != nil {
					f7f0f0.SecurityGroupIDs = aws.StringSlice(f7f0.Value.SecurityGroupIds)
				}
				if f7f0.Value.SubnetIds != nil {
					f7f0f0.SubnetIDs = aws.StringSlice(f7f0.Value.SubnetIds)
				}
				f7.EKSConfiguration = f7f0f0
			}
		}
		ko.Spec.Source = f7
	} else {
		ko.Spec.Source = nil
	}
	if resp.Scraper.StatusReason != nil {
		ko.Status.StatusReason = resp.Scraper.StatusReason
	} else {
		ko.Status.StatusReason = nil
	}
	if resp.Scraper.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Scraper.Tags)
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)

	// The API nests the state inside a Status object, which is flattened out of the
	// model (see ignore.field_paths), so copy it onto Status.StatusCode here. This
	// runs post-set-output, after the generated code has applied the response, so it
	// reflects what AWS just returned rather than the previous reconcile's value.
	if resp.Scraper.Status != nil && resp.Scraper.Status.StatusCode != "" {
		ko.Status.StatusCode = aws.String(string(resp.Scraper.Status.StatusCode))
	} else {
		ko.Status.StatusCode = nil
	}

	// A failed state is terminal: AWS will not retry it, and synced.when only ever
	// reports ACTIVE as synced, so without this the resource would requeue forever
	// with the reason buried in its status.
	if scraperHasFailed(&resource{ko}) {
		msg := "Scraper is in " + *ko.Status.StatusCode + " status"
		if ko.Status.StatusReason != nil {
			msg += ": " + *ko.Status.StatusReason
		}
		ackcondition.SetTerminal(&resource{ko}, corev1.ConditionTrue, &msg, nil)
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ScraperID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeScraperInput, error) {
	res := &svcsdk.DescribeScraperInput{}

	if r.ko.Status.ScraperID != nil {
		res.ScraperId = r.ko.Status.ScraperID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	// The API takes the scrape configuration as a base64-encoded blob wrapped in a
	// union, but users supply plain YAML in Spec.Configuration, matching the rule
	// groups and alert manager resources. The base64 conversion is handled by k8s.
	if desired.ko.Spec.Configuration != nil {
		input.ScrapeConfiguration = &svcsdktypes.ScrapeConfigurationMemberConfigurationBlob{
			Value: []byte(*desired.ko.Spec.Configuration),
		}
	}

	var resp *svcsdk.CreateScraperOutput
	_ = resp
	resp, err = rm.sdkapi.CreateScraper(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateScraper", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ScraperId != nil {
		ko.Status.ScraperID = resp.ScraperId
	} else {
		ko.Status.ScraperID = nil
	}
	if resp.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Tags)
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Spec.Tags != nil {
		msg := "Secondary sync required; resource will be requeued"
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, &msg, nil)
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateScraperInput, error) {
	res := &svcsdk.CreateScraperInput{}

	if r.ko.Spec.Alias != nil {
		res.Alias = r.ko.Spec.Alias
	}
	if r.ko.Spec.Destination != nil {
		var f1 svcsdktypes.Destination
		isInterfaceSet := false
		if r.ko.Spec.Destination.AmpConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AmpConfiguration"))
			}
			f1f0Parent := &svcsdktypes.DestinationMemberAmpConfiguration{}
			f1f0 := &svcsdktypes.AmpConfiguration{}
			if r.ko.Spec.Destination.AmpConfiguration.WorkspaceARN != nil {
				f1f0.WorkspaceArn = r.ko.Spec.Destination.AmpConfiguration.WorkspaceARN
			}
			f1f0Parent.Value = *f1f0
			f1 = f1f0Parent
			isInterfaceSet = true
		}
		res.Destination = f1
	}
	if r.ko.Spec.Source != nil {
		var f2 svcsdktypes.Source
		isInterfaceSet := false
		if r.ko.Spec.Source.EKSConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for EksConfiguration"))
			}
			f2f0Parent := &svcsdktypes.SourceMemberEksConfiguration{}
			f2f0 := &svcsdktypes.EksConfiguration{}
			if r.ko.Spec.Source.EKSConfiguration.ClusterARN != nil {
				f2f0.ClusterArn = r.ko.Spec.Source.EKSConfiguration.ClusterARN
			}
			if r.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs != nil {
				f2f0.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.Source.EKSConfiguration.SecurityGroupIDs)
			}
			if r.ko.Spec.Source.EKSConfiguration.SubnetIDs != nil {
				f2f0.SubnetIds = aws.ToStringSlice(r.ko.Spec.Source.EKSConfiguration.SubnetIDs)
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.Source = f2
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	// UpdateScraper accepts no source, so a source change can never converge.
	// Fail terminally rather than reconciling forever; the user must replace the
	// scraper. This is deliberately not is_immutable, whose CEL rule would reject
	// the adoption reconciler's own whole-spec write-back.
	if delta.DifferentAt("Spec.Source") {
		return nil, ackerr.NewTerminalError(fmt.Errorf(
			"Spec.Source is immutable; AMP requires replacing the scraper to change its source",
		))
	}

	updatedDesired := desired.DeepCopy()
	updatedDesired.SetStatus(latest)
	if delta.DifferentAt("Spec.Tags") {
		err = rm.syncTags(ctx, desired, latest)
		if err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return rm.concreteResource(updatedDesired), nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	// Same conversion as on create. This has to run post-build because the hook
	// point before it executes ahead of newUpdateRequestPayload, so input is nil there.
	if delta.DifferentAt("Spec.Configuration") && desired.ko.Spec.Configuration != nil {
		input.ScrapeConfiguration = &svcsdktypes.ScrapeConfigurationMemberConfigurationBlob{
			Value: []byte(*desired.ko.Spec.Configuration),
		}
	}

	var resp *svcsdk.UpdateScraperOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateScraper(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateScraper", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ScraperId != nil {
		ko.Status.ScraperID = resp.ScraperId
	} else {
		ko.Status.ScraperID = nil
	}
	if resp.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Tags)
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateScraperInput, error) {
	res := &svcsdk.UpdateScraperInput{}

	if r.ko.Spec.Alias != nil {
		res.Alias = r.ko.Spec.Alias
	}
	if r.ko.Spec.Destination != nil {
		var f2 svcsdktypes.Destination
		isInterfaceSet := false
		if r.ko.Spec.Destination.AmpConfiguration != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for AmpConfiguration"))
			}
			f2f0Parent := &svcsdktypes.DestinationMemberAmpConfiguration{}
			f2f0 := &svcsdktypes.AmpConfiguration{}
			if r.ko.Spec.Destination.AmpConfiguration.WorkspaceARN != nil {
				f2f0.WorkspaceArn = r.ko.Spec.Destination.AmpConfiguration.WorkspaceARN
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.Destination = f2
	}
	if r.ko.Status.ScraperID != nil {
		res.ScraperId = r.ko.Status.ScraperID
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()

	// A scraper already in DELETING would reject another DeleteScraper, so requeue
	// without calling it again.
	if scraperDeleting(r) {
		return nil, requeueWaitWhileDeleting
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteScraperOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteScraper(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteScraper", err)

	// DeleteScraper only starts the deletion. Requeue so the finalizer is dropped
	// only once DescribeScraper stops finding the scraper, rather than leaving the
	// CR gone while AWS is still tearing the scraper down.
	if err == nil {
		return nil, requeueWaitWhileDeleting
	}

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteScraperInput, error) {
	res := &svcsdk.DeleteScraperInput{}

	if r.ko.Status.ScraperID != nil {
		res.ScraperId = r.ko.Status.ScraperID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Scraper,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
