// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package rule_groups_namespace

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/prometheusservice-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=prometheusservice.services.k8s.aws,resources=workspaces,verbs=get;list
// +kubebuilder:rbac:groups=prometheusservice.services.k8s.aws,resources=workspaces/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.WorkspaceRef != nil {
		ko.Spec.WorkspaceID = nil
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForWorkspaceID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.RuleGroupsNamespace) error {

	if ko.Spec.WorkspaceRef != nil && ko.Spec.WorkspaceID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("WorkspaceID", "WorkspaceRef")
	}
	if ko.Spec.WorkspaceRef == nil && ko.Spec.WorkspaceID == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("WorkspaceID", "WorkspaceRef")
	}
	return nil
}

// resolveReferenceForWorkspaceID reads the resource referenced
// from WorkspaceRef field and sets the WorkspaceID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForWorkspaceID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.RuleGroupsNamespace,
) (hasReferences bool, err error) {
	if ko.Spec.WorkspaceRef != nil && ko.Spec.WorkspaceRef.From != nil {
		hasReferences = true
		arr := ko.Spec.WorkspaceRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: WorkspaceRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &svcapitypes.Workspace{}
		if err := getReferencedResourceState_Workspace(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.WorkspaceID = (*string)(obj.Status.WorkspaceID)
	}

	return hasReferences, nil
}

// getReferencedResourceState_Workspace looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Workspace(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.Workspace,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeReady &&
			cond.Status == corev1.ConditionFalse &&
			*cond.Reason == ackcondition.TerminalReason {
			return ackerr.ResourceReferenceTerminalFor(
				"Workspace",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Workspace",
			namespace, name)
	}
	var refResourceReady bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeReady &&
			cond.Status == corev1.ConditionTrue {
			refResourceReady = true
		}
	}
	if !refResourceReady {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Workspace",
			namespace, name)
	}
	if obj.Status.WorkspaceID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Workspace",
			namespace, name,
			"Status.WorkspaceID")
	}
	return nil
}
