// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LoggingConfigurationSpec defines the desired state of LoggingConfiguration.
type LoggingConfigurationSpec struct {

	// The ARN of the CloudWatch log group to which the vended log data will be
	// published. This log group must exist prior to calling this operation.

	// +kubebuilder:validation:Required

	LogGroupARN *string `json:"logGroupARN"`
	// The ID of the workspace to create the logging configuration for.

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"

	WorkspaceID *string `json:"workspaceID,omitempty"`

	WorkspaceRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"workspaceRef,omitempty"`
}

// LoggingConfigurationStatus defines the observed state of LoggingConfiguration
type LoggingConfigurationStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The current status of the logging configuration.
	// +kubebuilder:validation:Optional
	StatusCode *string `json:"statusCode,omitempty"`
	// If failed, the reason for the failure.
	// +kubebuilder:validation:Optional
	StatusReason *string `json:"statusReason,omitempty"`
}

// LoggingConfiguration is the Schema for the LoggingConfigurations API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="LOG-GROUP-ARN",type=string,priority=0,JSONPath=`.spec.logGroupARN`
// +kubebuilder:printcolumn:name="WORKSPACE-ID",type=string,priority=0,JSONPath=`.spec.workspaceID`
type LoggingConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LoggingConfigurationSpec   `json:"spec,omitempty"`
	Status            LoggingConfigurationStatus `json:"status,omitempty"`
}

// LoggingConfigurationList contains a list of LoggingConfiguration
// +kubebuilder:object:root=true
type LoggingConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoggingConfiguration `json:"items"`
}

func init() {
	SchemeBuilder.Register(&LoggingConfiguration{}, &LoggingConfigurationList{})
}
