// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RuleGroupsNamespaceSpec defines the desired state of RuleGroupsNamespace.
type RuleGroupsNamespaceSpec struct {

	// The name for the new rule groups namespace.

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required

	Name *string `json:"name"`
	// The list of tag keys and values to associate with the rule groups namespace.

	Tags map[string]*string `json:"tags,omitempty"`
	// The ID of the workspace to add the rule groups namespace.

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"

	WorkspaceID *string `json:"workspaceID,omitempty"`

	WorkspaceRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"workspaceRef,omitempty"`

	// +kubebuilder:validation:Required

	Configuration *string `json:"configuration"`
}

// RuleGroupsNamespaceStatus defines the observed state of RuleGroupsNamespace
type RuleGroupsNamespaceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// A structure that returns the current status of the rule groups namespace.
	// +kubebuilder:validation:Optional
	Status *RuleGroupsNamespaceStatus_SDK `json:"status,omitempty"`
}

// RuleGroupsNamespace is the Schema for the RuleGroupsNamespaces API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="WORKSPACE-ID",type=string,priority=0,JSONPath=`.spec.workspaceID`
// +kubebuilder:resource:shortName=rgn
type RuleGroupsNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RuleGroupsNamespaceSpec   `json:"spec,omitempty"`
	Status            RuleGroupsNamespaceStatus `json:"status,omitempty"`
}

// RuleGroupsNamespaceList contains a list of RuleGroupsNamespace
// +kubebuilder:object:root=true
type RuleGroupsNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleGroupsNamespace `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RuleGroupsNamespace{}, &RuleGroupsNamespaceList{})
}
