// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ScraperSpec defines the desired state of Scraper.
type ScraperSpec struct {

	// (optional) An alias to associate with the scraper. This is for your use,
	// and does not need to be unique.
	//
	// Regex Pattern: `^[0-9A-Za-z][-.0-9A-Z_a-z]*$`
	Alias *string `json:"alias,omitempty"`
	// The Amazon Managed Service for Prometheus workspace to send metrics to.
	// +kubebuilder:validation:Required
	Destination *Destination `json:"destination"`
	// The Amazon EKS cluster from which the scraper will collect metrics.
	// +kubebuilder:validation:Required
	Source *Source `json:"source"`
	// (Optional) The list of tag keys and values to associate with the scraper.
	Tags map[string]*string `json:"tags,omitempty"`
	// +kubebuilder:validation:Required
	Configuration *string `json:"configuration"`
}

// ScraperStatus defines the observed state of Scraper
type ScraperStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The Amazon Resource Name (ARN) of the IAM role that provides permissions
	// for the scraper to discover and collect metrics on your behalf.
	//
	// For example, arn:aws:iam::123456789012:role/service-role/AmazonGrafanaServiceRole-12example.
	// +kubebuilder:validation:Optional
	RoleARN *string `json:"roleARN,omitempty"`
	// The ID of the new scraper.
	//
	// Regex Pattern: `^[0-9A-Za-z][-.0-9A-Z_a-z]*$`
	// +kubebuilder:validation:Optional
	ScraperID *string `json:"scraperID,omitempty"`
	// A structure that displays the current status of the scraper.
	// +kubebuilder:validation:Optional
	Status *ScraperStatus_SDK `json:"status,omitempty"`
	// If there is a failure, the reason for the failure.
	// +kubebuilder:validation:Optional
	StatusReason *string `json:"statusReason,omitempty"`
}

// Scraper is the Schema for the Scrapers API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ALIAS",type=string,priority=0,JSONPath=`.spec.alias`
type Scraper struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ScraperSpec   `json:"spec,omitempty"`
	Status            ScraperStatus `json:"status,omitempty"`
}

// ScraperList contains a list of Scraper
// +kubebuilder:object:root=true
type ScraperList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Scraper `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Scraper{}, &ScraperList{})
}
