// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The details of an alert manager definition. It is the configuration for the
// alert manager, including information about receivers for routing alerts.
type AlertManagerDefinitionDescription struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The base-64 encoded blob that is alert manager definition.
	//
	// For details about the alert manager definition, see AlertManagedDefinitionData
	// (https://docs.aws.amazon.com/prometheus/latest/APIReference/yaml-AlertManagerDefinitionData.html).
	Data       []byte       `json:"data,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The status of the alert manager.
	Status *AlertManagerDefinitionStatus_SDK `json:"status,omitempty"`
}

// The status of the alert manager.
type AlertManagerDefinitionStatus_SDK struct {
	// State of an AlertManagerDefinition.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// The AmpConfiguration structure defines the Amazon Managed Service for Prometheus
// instance a scraper should send metrics to.
type AmpConfiguration struct {
	// An ARN identifying a Workspace.
	WorkspaceARN *string `json:"workspaceARN,omitempty"`
}

// Contains information about the logging configuration for the workspace.
type LoggingConfigurationMetadata struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	LogGroupARN *string      `json:"logGroupARN,omitempty"`
	ModifiedAt  *metav1.Time `json:"modifiedAt,omitempty"`
	// The status of the logging configuration.
	Status *LoggingConfigurationStatus_SDK `json:"status,omitempty"`
	// A workspace ID.
	Workspace *string `json:"workspace,omitempty"`
}

// The status of the logging configuration.
type LoggingConfigurationStatus_SDK struct {
	// State of a logging configuration.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// The details about one rule groups namespace.
type RuleGroupsNamespaceDescription struct {
	// An ARN identifying a rule groups namespace.
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The rule groups namespace data.
	Data       []byte       `json:"data,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The name of the namespace that the rule group belong to.
	Name *string `json:"name,omitempty"`
	// The status information about a rule groups namespace.
	Status *RuleGroupsNamespaceStatus_SDK `json:"status,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// The status information about a rule groups namespace.
type RuleGroupsNamespaceStatus_SDK struct {
	// State of a namespace.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// The high-level information about a rule groups namespace. To retrieve more
// information, use DescribeRuleGroupsNamespace.
type RuleGroupsNamespaceSummary struct {
	// An ARN identifying a rule groups namespace.
	ARN        *string      `json:"arn,omitempty"`
	CreatedAt  *metav1.Time `json:"createdAt,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The name of the namespace that the rule group belong to.
	Name *string `json:"name,omitempty"`
	// The status information about a rule groups namespace.
	Status *RuleGroupsNamespaceStatus_SDK `json:"status,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// The ScraperDescription structure contains the full details about one scraper
// in your account.
type ScraperDescription struct {
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	LastModifiedAt *metav1.Time `json:"lastModifiedAt,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// The ScraperSummary structure contains a summary of the details about one
// scraper in your account.
type ScraperSummary struct {
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	LastModifiedAt *metav1.Time `json:"lastModifiedAt,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// Information about a field passed into a request that resulted in an exception.
type ValidationExceptionField struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// The full details about one Amazon Managed Service for Prometheus workspace
// in your account.
type WorkspaceDescription struct {
	// A user-assigned workspace alias.
	Alias *string `json:"alias,omitempty"`
	// An ARN identifying a Workspace.
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// A KMS Key ARN.
	KMSKeyARN          *string `json:"kmsKeyARN,omitempty"`
	PrometheusEndpoint *string `json:"prometheusEndpoint,omitempty"`
	// The status of the workspace.
	Status *WorkspaceStatus_SDK `json:"status,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
	// A workspace ID.
	WorkspaceID *string `json:"workspaceID,omitempty"`
}

// The status of the workspace.
type WorkspaceStatus_SDK struct {
	// State of a workspace.
	StatusCode *string `json:"statusCode,omitempty"`
}

// The information about one Amazon Managed Service for Prometheus workspace
// in your account.
type WorkspaceSummary struct {
	// A user-assigned workspace alias.
	Alias *string `json:"alias,omitempty"`
	// An ARN identifying a Workspace.
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// A KMS Key ARN.
	KMSKeyARN *string `json:"kmsKeyARN,omitempty"`
	// The status of the workspace.
	Status *WorkspaceStatus_SDK `json:"status,omitempty"`
	// A tag associated with a resource.
	Tags map[string]*string `json:"tags,omitempty"`
	// A workspace ID.
	WorkspaceID *string `json:"workspaceID,omitempty"`
}
