// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Represents the properties of an alert manager definition.
type AlertManagerDefinitionDescription struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The alert manager definition data.
	Data       []byte       `json:"data,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// Represents the status of a definition.
	Status *AlertManagerDefinitionStatus_SDK `json:"status,omitempty"`
}

// Represents the status of a definition.
type AlertManagerDefinitionStatus_SDK struct {
	// State of an alert manager definition.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// Represents the properties of a logging configuration metadata.
type LoggingConfigurationMetadata struct {
	CreatedAt   *metav1.Time `json:"createdAt,omitempty"`
	LogGroupARN *string      `json:"logGroupARN,omitempty"`
	ModifiedAt  *metav1.Time `json:"modifiedAt,omitempty"`
	// Represents the status of a logging configuration.
	Status *LoggingConfigurationStatus_SDK `json:"status,omitempty"`
	// A workspace ID.
	Workspace *string `json:"workspace,omitempty"`
}

// Represents the status of a logging configuration.
type LoggingConfigurationStatus_SDK struct {
	// State of a logging configuration.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// Represents a description of the rule groups namespace.
type RuleGroupsNamespaceDescription struct {
	// An ARN identifying a rule groups namespace.
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The rule groups namespace data.
	Data       []byte       `json:"data,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The namespace name that the rule group belong to.
	Name *string `json:"name,omitempty"`
	// Represents the status of a namespace.
	Status *RuleGroupsNamespaceStatus_SDK `json:"status,omitempty"`
	// The list of tags assigned to the resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// Represents the status of a namespace.
type RuleGroupsNamespaceStatus_SDK struct {
	// State of a namespace.
	StatusCode   *string `json:"statusCode,omitempty"`
	StatusReason *string `json:"statusReason,omitempty"`
}

// Represents a summary of the rule groups namespace.
type RuleGroupsNamespaceSummary struct {
	// An ARN identifying a rule groups namespace.
	ARN        *string      `json:"arn,omitempty"`
	CreatedAt  *metav1.Time `json:"createdAt,omitempty"`
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The namespace name that the rule group belong to.
	Name *string `json:"name,omitempty"`
	// Represents the status of a namespace.
	Status *RuleGroupsNamespaceStatus_SDK `json:"status,omitempty"`
	// The list of tags assigned to the resource.
	Tags map[string]*string `json:"tags,omitempty"`
}

// Stores information about a field passed inside a request that resulted in
// an exception.
type ValidationExceptionField struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Represents the properties of a workspace.
type WorkspaceDescription struct {
	// A user-assigned workspace alias.
	Alias *string `json:"alias,omitempty"`
	// An ARN identifying a Workspace.
	ARN                *string      `json:"arn,omitempty"`
	CreatedAt          *metav1.Time `json:"createdAt,omitempty"`
	PrometheusEndpoint *string      `json:"prometheusEndpoint,omitempty"`
	// Represents the status of a workspace.
	Status *WorkspaceStatus_SDK `json:"status,omitempty"`
	// The list of tags assigned to the resource.
	Tags map[string]*string `json:"tags,omitempty"`
	// A workspace ID.
	WorkspaceID *string `json:"workspaceID,omitempty"`
}

// Represents the status of a workspace.
type WorkspaceStatus_SDK struct {
	// State of a workspace.
	StatusCode *string `json:"statusCode,omitempty"`
}

// Represents a summary of the properties of a workspace.
type WorkspaceSummary struct {
	// A user-assigned workspace alias.
	Alias *string `json:"alias,omitempty"`
	// An ARN identifying a Workspace.
	ARN       *string      `json:"arn,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Represents the status of a workspace.
	Status *WorkspaceStatus_SDK `json:"status,omitempty"`
	// The list of tags assigned to the resource.
	Tags map[string]*string `json:"tags,omitempty"`
	// A workspace ID.
	WorkspaceID *string `json:"workspaceID,omitempty"`
}
